// <auto-generated />
using DietCraft.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DietCraft.API.Migrations
{
    [DbContext(typeof(DietCraftContext))]
    [Migration("20240213153608_bulkInsert")]
    partial class bulkInsert
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("DietCraft.API.Entities.Diet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DietTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserIdIfCustom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isCustom")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DietTypeId");

                    b.ToTable("Diets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DietTypeId = 1,
                            Name = "Dieta wegańska",
                            UserIdIfCustom = 0,
                            isCustom = false
                        },
                        new
                        {
                            Id = 2,
                            DietTypeId = 2,
                            Name = "Dieta keto",
                            UserIdIfCustom = 0,
                            isCustom = false
                        },
                        new
                        {
                            Id = 3,
                            DietTypeId = 3,
                            Name = "Dieta zbalansowana",
                            UserIdIfCustom = 1,
                            isCustom = true
                        },
                        new
                        {
                            Id = 4,
                            DietTypeId = 4,
                            Name = "Dieta niskowęglowodanowa",
                            UserIdIfCustom = 2,
                            isCustom = true
                        },
                        new
                        {
                            Id = 5,
                            DietTypeId = 5,
                            Name = "Dieta białkowa",
                            UserIdIfCustom = 3,
                            isCustom = true
                        });
                });

            modelBuilder.Entity("DietCraft.API.Entities.DietType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CarbPercent")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FatPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("ProteinPercent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DietTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarbPercent = (byte)50,
                            FatPercent = (byte)25,
                            Name = "Wege",
                            ProteinPercent = (byte)25
                        },
                        new
                        {
                            Id = 2,
                            CarbPercent = (byte)10,
                            FatPercent = (byte)60,
                            Name = "Keto",
                            ProteinPercent = (byte)30
                        },
                        new
                        {
                            Id = 3,
                            CarbPercent = (byte)40,
                            FatPercent = (byte)30,
                            Name = "Balans",
                            ProteinPercent = (byte)30
                        },
                        new
                        {
                            Id = 4,
                            CarbPercent = (byte)20,
                            FatPercent = (byte)40,
                            Name = "Niskowęglowodanowa",
                            ProteinPercent = (byte)40
                        },
                        new
                        {
                            Id = 5,
                            CarbPercent = (byte)45,
                            FatPercent = (byte)35,
                            Name = "Białkowa",
                            ProteinPercent = (byte)20
                        });
                });

            modelBuilder.Entity("DietCraft.API.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarbGram")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FatGram")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kcal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProteinGram")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarbGram = 0,
                            FatGram = 0,
                            IsVegan = true,
                            Kcal = 0,
                            Name = "Jajka",
                            Price = 1.0m,
                            ProteinGram = 0
                        },
                        new
                        {
                            Id = 2,
                            CarbGram = 0,
                            FatGram = 0,
                            IsVegan = false,
                            Kcal = 0,
                            Name = "Szpinak",
                            Price = 2.0m,
                            ProteinGram = 0
                        },
                        new
                        {
                            Id = 3,
                            CarbGram = 0,
                            FatGram = 0,
                            IsVegan = true,
                            Kcal = 0,
                            Name = "Pomidory",
                            Price = 3.0m,
                            ProteinGram = 0
                        },
                        new
                        {
                            Id = 4,
                            CarbGram = 0,
                            FatGram = 0,
                            IsVegan = false,
                            Kcal = 0,
                            Name = "Kurczak",
                            Price = 4.0m,
                            ProteinGram = 0
                        },
                        new
                        {
                            Id = 5,
                            CarbGram = 0,
                            FatGram = 0,
                            IsVegan = true,
                            Kcal = 0,
                            Name = "Oliwa z oliwek",
                            Price = 5.0m,
                            ProteinGram = 0
                        },
                        new
                        {
                            Id = 6,
                            CarbGram = 0,
                            FatGram = 0,
                            IsVegan = false,
                            Kcal = 0,
                            Name = "Brokuły",
                            Price = 6.0m,
                            ProteinGram = 0
                        },
                        new
                        {
                            Id = 7,
                            CarbGram = 0,
                            FatGram = 0,
                            IsVegan = true,
                            Kcal = 0,
                            Name = "Cebula",
                            Price = 7.0m,
                            ProteinGram = 0
                        },
                        new
                        {
                            Id = 8,
                            CarbGram = 0,
                            FatGram = 0,
                            IsVegan = false,
                            Kcal = 0,
                            Name = "Ryż",
                            Price = 8.0m,
                            ProteinGram = 0
                        },
                        new
                        {
                            Id = 9,
                            CarbGram = 0,
                            FatGram = 0,
                            IsVegan = true,
                            Kcal = 0,
                            Name = "Marchewka",
                            Price = 9.0m,
                            ProteinGram = 0
                        },
                        new
                        {
                            Id = 10,
                            CarbGram = 0,
                            FatGram = 0,
                            IsVegan = false,
                            Kcal = 0,
                            Name = "Tuńczyk",
                            Price = 10.0m,
                            ProteinGram = 0
                        },
                        new
                        {
                            Id = 11,
                            CarbGram = 0,
                            FatGram = 0,
                            IsVegan = true,
                            Kcal = 0,
                            Name = "Ogórki",
                            Price = 11.0m,
                            ProteinGram = 0
                        },
                        new
                        {
                            Id = 12,
                            CarbGram = 0,
                            FatGram = 0,
                            IsVegan = false,
                            Kcal = 0,
                            Name = "Ser",
                            Price = 12.0m,
                            ProteinGram = 0
                        });
                });

            modelBuilder.Entity("DietCraft.API.Entities.IngredientsForMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Grams")
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Mililiters")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MealId");

                    b.ToTable("IngredientsForMeals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grams = 100m,
                            IngredientId = 1,
                            IsOptional = false,
                            MealId = 1,
                            Mililiters = 0m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            Grams = 150m,
                            IngredientId = 2,
                            IsOptional = true,
                            MealId = 1,
                            Mililiters = 0m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            Grams = 50m,
                            IngredientId = 3,
                            IsOptional = true,
                            MealId = 1,
                            Mililiters = 0m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            Grams = 80m,
                            IngredientId = 4,
                            IsOptional = true,
                            MealId = 1,
                            Mililiters = 0m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            Grams = 100m,
                            IngredientId = 3,
                            IsOptional = false,
                            MealId = 2,
                            Mililiters = 0m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            Grams = 80m,
                            IngredientId = 5,
                            IsOptional = false,
                            MealId = 2,
                            Mililiters = 0m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            Grams = 120m,
                            IngredientId = 6,
                            IsOptional = false,
                            MealId = 2,
                            Mililiters = 0m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 8,
                            Grams = 150m,
                            IngredientId = 4,
                            IsOptional = false,
                            MealId = 3,
                            Mililiters = 0m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 9,
                            Grams = 100m,
                            IngredientId = 8,
                            IsOptional = false,
                            MealId = 3,
                            Mililiters = 0m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 10,
                            Grams = 80m,
                            IngredientId = 9,
                            IsOptional = true,
                            MealId = 3,
                            Mililiters = 0m,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("DietCraft.API.Entities.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserIdIfCustom")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsVegan = false,
                            Name = "Jajecznica",
                            UserIdIfCustom = 0
                        },
                        new
                        {
                            Id = 2,
                            IsVegan = true,
                            Name = "Sałatka grecka",
                            UserIdIfCustom = 0
                        },
                        new
                        {
                            Id = 3,
                            IsVegan = false,
                            Name = "Kurczak z ryżem",
                            UserIdIfCustom = 0
                        });
                });

            modelBuilder.Entity("DietCraft.API.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionHTML")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MealId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleHTML")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isStepByStep")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescriptionHTML = "<p>Delicious broccoli salad recipe.</p>",
                            MealId = 1,
                            Name = "Przepis 1",
                            TitleHTML = "<h1>Broccoli Salad</h1>",
                            isStepByStep = true
                        },
                        new
                        {
                            Id = 2,
                            DescriptionHTML = "<p>Perfectly grilled chicken recipe.</p>",
                            MealId = 2,
                            Name = "Przepis 2",
                            TitleHTML = "<h1>Grilled Chicken</h1>",
                            isStepByStep = true
                        },
                        new
                        {
                            Id = 3,
                            DescriptionHTML = "<p>Simple and tasty salmon fillet recipe.</p>",
                            MealId = 3,
                            Name = "Przepis 3",
                            TitleHTML = "<h1>Salmon Fillet</h1>",
                            isStepByStep = true
                        });
                });

            modelBuilder.Entity("DietCraft.API.Entities.Role", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "User"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = (byte)4,
                            Name = "Viewer"
                        },
                        new
                        {
                            Id = (byte)5,
                            Name = "Tester"
                        });
                });

            modelBuilder.Entity("DietCraft.API.Entities.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lista zakupów 1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lista zakupów 2",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lista zakupów 3",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lista zakupów 4",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lista zakupów 5",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("DietCraft.API.Entities.ShoppingListIngredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShoppingListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ShoppingListIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientId = 1,
                            Quantity = 2,
                            ShoppingListId = 1
                        },
                        new
                        {
                            Id = 2,
                            IngredientId = 2,
                            Quantity = 1,
                            ShoppingListId = 1
                        },
                        new
                        {
                            Id = 3,
                            IngredientId = 3,
                            Quantity = 3,
                            ShoppingListId = 2
                        },
                        new
                        {
                            Id = 4,
                            IngredientId = 4,
                            Quantity = 2,
                            ShoppingListId = 3
                        },
                        new
                        {
                            Id = 5,
                            IngredientId = 5,
                            Quantity = 1,
                            ShoppingListId = 4
                        });
                });

            modelBuilder.Entity("DietCraft.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "$2a$10$q8a4rK3A7wblUgM.mAwgheFj.vm9va86QL84yDYz8HA8kwJfLtp9u",
                            RoleId = (byte)1,
                            UserName = "john_doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            PasswordHash = "$2a$10$kpgE5duPhmrRrICec7HiGupGOQ.VwmQCHri0/WxsNL2PHAMT/Ywkm",
                            RoleId = (byte)2,
                            UserName = "alice_smith"
                        },
                        new
                        {
                            Id = 3,
                            Email = "bob@example.com",
                            FirstName = "Bob",
                            LastName = "Johnson",
                            PasswordHash = "$2a$10$zoPclQTUbuUfmMhxNJw6eutJN4SDvuhDQPgr43z1JXZ4VLuG.3PUK",
                            RoleId = (byte)3,
                            UserName = "bob_johnson"
                        },
                        new
                        {
                            Id = 4,
                            Email = "emily@example.com",
                            FirstName = "Emily",
                            LastName = "Brown",
                            PasswordHash = "$2a$10$.NBMSQ9YQ1iP.XeG59sp6erjnNWHKvz3.PJD11lKPU86OzTiGTMSa",
                            RoleId = (byte)4,
                            UserName = "emily_brown"
                        },
                        new
                        {
                            Id = 5,
                            Email = "david@example.com",
                            FirstName = "David",
                            LastName = "Wilson",
                            PasswordHash = "$2a$10$TJA2TVHEN/E1chHMI58Mc.OzzBJwoYAkJDCulJ/ruW7TjKvc8/3IC",
                            RoleId = (byte)5,
                            UserName = "david_wilson"
                        });
                });

            modelBuilder.Entity("DietCraft.API.Entities.UserDiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DietId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxKcal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DietId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDiets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DietId = 1,
                            MaxKcal = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DietId = 2,
                            MaxKcal = 1800,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DietId = 3,
                            MaxKcal = 2200,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            DietId = 4,
                            MaxKcal = 1900,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            DietId = 5,
                            MaxKcal = 2100,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("DietCraft.API.Entities.Diet", b =>
                {
                    b.HasOne("DietCraft.API.Entities.DietType", "DietType")
                        .WithMany()
                        .HasForeignKey("DietTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietType");
                });

            modelBuilder.Entity("DietCraft.API.Entities.IngredientsForMeal", b =>
                {
                    b.HasOne("DietCraft.API.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietCraft.API.Entities.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("DietCraft.API.Entities.Recipe", b =>
                {
                    b.HasOne("DietCraft.API.Entities.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("DietCraft.API.Entities.ShoppingList", b =>
                {
                    b.HasOne("DietCraft.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietCraft.API.Entities.ShoppingListIngredients", b =>
                {
                    b.HasOne("DietCraft.API.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietCraft.API.Entities.ShoppingList", "ShoppingList")
                        .WithMany("ShoppingListIngredients")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("DietCraft.API.Entities.User", b =>
                {
                    b.HasOne("DietCraft.API.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DietCraft.API.Entities.UserDiet", b =>
                {
                    b.HasOne("DietCraft.API.Entities.Diet", "Diet")
                        .WithMany()
                        .HasForeignKey("DietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietCraft.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietCraft.API.Entities.ShoppingList", b =>
                {
                    b.Navigation("ShoppingListIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
